
User.destroy_all
Post.destroy_all
Favorite.destroy_all

gaga = User.create(honorific: "Ms.", first_name: "Lady", last_name: "Gaga", email: "ladygaga@ladygaga.com", password: "yolo", voice_type: "Mezzo-Soprano", biography: "American Mezzo-Soprano", degree: "Master's", institution: "University of Wisconsin", website: "https://www.ladygaga.com/", pronouns: "she, her, hers")
britney = User.create(honorific: "Mrs.", first_name: "Britney", last_name: "Spears", email: "britney@britney.com", password: "yolo", voice_type: "Contralto", biography: "Contralto Singer", degree: "High School Diploma", institution: "Sherman Oaks High School", website: "https://www.britneyspears.com/", pronouns: "she, her, hers")
bieber = User.create(honorific: "Mr.", first_name: "Justin", last_name: "Bieber", email: "bieber@me.com", password: "yolo", voice_type: "Tenor", biography: "American Tenor.", degree: "Bachelor's", institution: "University of Toronto", website: "https://www.justinbiebermusic.com/", pronouns: "he, him, his")
director1 = User.create(honorific: "Mr.", first_name: "John", last_name: "Smith", email: "john@me.com", password: "yolo", voice_type: "N/A", biography: "Director of a Church", degree: "Master's", institution: "McGill University", website: "www.johnsmith.com", pronouns: "he, him, his and they, them, theirs")
director2 = User.create(honorific: "Mrs.", first_name: "Mary Kay", last_name: "Place", email: "mary@me.com", password: "yolo", voice_type: "N/A", biography: "Director of a Theatre", degree: "Master's", institution: "The Juilliard School", website: "www.mary.com", pronouns: "she, her, hers")


post1 = Post.create(performance_type: "Concert", voice_type: "Mezzo-Soprano", time: "2000-01-01T12:50:00.000Z", date: "2020-12-13", repertoire: "Brahms Requiem", notes: "Must be an excellent sightreader.", venue_name: "Chicago Symphony Orchestra", street_address: "220 S Michigan Ave", address_line_two: "", city: "Chicago", state: "IL", zip: 60604, contact_first_name: gaga.first_name, contact_last_name: gaga.last_name, contact_email: gaga.email, paid: true, user: gaga, user_honorific: gaga.honorific)
post2 = Post.create(performance_type: "Religious Service", voice_type: "Contralto", time: "2000-01-01T12:50:00.000Z", date: "2020-12-25", repertoire: "Britten and Hovhaness", notes: "Must be an excellent sightreader. There is no rehearsal beforehand.", venue_name: "New Friends Wesleyan Church", street_address: "174 Old Sutton Rd", address_line_two: "", city: "Barrington", state: "IL", zip: 60010, contact_first_name: bieber.first_name, contact_last_name: bieber.last_name, contact_email: bieber.email, paid: true, user: bieber, user_honorific: bieber.honorific)
post3 = Post.create(performance_type: "Rehearsal", voice_type: "Countertenor", time: "2000-01-01T12:50:00.000Z", date: "2020-12-20", repertoire: "Bach Magnificat", notes: "I need a mezzo or alto to fill in for a rehearsal. Must know the Bach Magnificat alto solos.", venue_name: "St. John Cantius Church", street_address: "825 N Carpenter St", address_line_two: "", city: "Chicago", state: "IL", zip: 60642, contact_first_name: britney.first_name, contact_last_name: britney.last_name, contact_email: britney.email, paid: true, user: britney, user_honorific: britney.honorific)
post4 = Post.create(performance_type: "Religious Service", voice_type: "Soprano", time: "2000-01-01T10:00:00.000Z", date: "2020-10-18", repertoire: "Lauridsen and Spirituals", notes: "I need a strong sightreader. There is no rehearsal and you will be the only soprano.", venue_name: "St. John Vianney Catholic Church", street_address: "46 N Wolf Rd", address_line_two: "", city: "Northlake", state: "IL", zip: 60164, contact_first_name: director1.first_name, contact_last_name: director1.last_name, contact_email: director1.email, paid: true, user: director1, user_honorific: director1.honorific)
post5 = Post.create(performance_type: "Religious Service", voice_type: "Alto", time: "2000-01-01T10:00:00.000Z", date: "2020-10-18", repertoire: "Lauridsen and Spirituals", notes: "I need a strong sightreader. There is no rehearsal and you will be the only alto.", venue_name: "St. John Vianney Catholic Church", street_address: "46 N Wolf Rd", address_line_two: "", city: "Northlake", state: "IL", zip: 60164, contact_first_name: director1.first_name, contact_last_name: director1.last_name, contact_email: director1.email, paid: true, user: director1, user_honorific: director1.honorific)
post6 = Post.create(performance_type: "Religious Service", voice_type: "Tenor", time: "2000-01-01T10:00:00.000Z", date: "2020-10-18", repertoire: "Lauridsen and Spirituals", notes: "I need a strong sightreader. There is no rehearsal and you will be the only tenor.", venue_name: "St. John Vianney Catholic Church", street_address: "46 N Wolf Rd", address_line_two: "", city: "Northlake", state: "IL", zip: 60164, contact_first_name: director1.first_name, contact_last_name: director1.last_name, contact_email: director1.email, paid: true, user: director1, user_honorific: director1.honorific)
post7 = Post.create(performance_type: "Religious Service", voice_type: "Bass", time: "2000-01-01T10:00:00.000Z", date: "2020-10-18", repertoire: "Lauridsen and Spirituals", notes: "I need a strong sightreader. There is no rehearsal and you will be the only bass.", venue_name: "St. John Vianney Catholic Church", street_address: "46 N Wolf Rd", address_line_two: "", city: "Northlake", state: "IL", zip: 60164, contact_first_name: director1.first_name, contact_last_name: director1.last_name, contact_email: director1.email, paid: true, user: director1, user_honorific: director1.honorific)

